<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <RootNamespace>BocaSystems.Sdk.Sample</RootNamespace>
    <AssemblyName>BocaSystems.Sdk.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BocaSystems.Sdk\BocaSystems.Sdk.csproj" />
  </ItemGroup>

</Project>
